version: '3'

services:
  app:
    image: mcr.microsoft.com/devcontainers/python:0-3.11
    # command: python app.py
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/app
  openapi-generator:
    image: openapitools/openapi-generator-cli:latest
    volumes:
      - ..:/app
    command: ["tail", "-f", "/dev/null"]